server:
  port: 8002
spring:
  thymeleaf:
    cache: false
  application:
    name: userconsumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka,http://localhost:8090/eureka